workflows:
  default-workflow:
    name: Personal Website Flow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - cd . && flutter packages pub get
      - cd . && flutter config --enable-web
      - |
        # build web
        cd .
        flutter build web --web-renderer canvaskit --release
        cd build/web
        7z a -r ../web.zip ./*
      - firebase deploy --token "$FIREBASE_TOKEN"
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
      email:
        recipients:
          - esentakos@yahoo.gr
