workflows:
  default-workflow:
    name: Personal Website Flow
    max_build_duration: 60
    environment:
      vars:
        FIREBASE_TOKEN: Encrypted(Z0FBQUFBQmdYbDJTRzJfUUx5WmpranItS0tBUmJGOVplbTNRMm9vUDVabVBMTUR0b0FjTEFFQ2FXR2E4bVVVdURfN0FmalRaYTVsTjg3Z2ktMExlc0l0RHlEMUR3c2dUOVpyQmdHNXFNRE81TzlaZWx1SGZ3Y0F6Nlg3bVFMX1oydnNjMUZ2Wmc1Sld3ZV9zUmtzX0d0NkZMbC10WXFKTFVrMkVxMDhMNDBhWUMzalh4YmhoajJGMU9TUjJ5M3FTMUx4VVhVdnc2WlBfQUNqb2w4dmhYSlBMa0NDaEtqYzZ1dz09)
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - cd . && flutter packages pub get
      - cd . && flutter config --enable-web
      - |
        # build web
        cd .
        flutter build web --web-renderer canvaskit --release
        cd build/web
        7z a -r ../web.zip ./*
      - firebase deploy --token "$FIREBASE_TOKEN"
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - esentakos@yahoo.gr
